name: pan-dashboard
services:
  clickhouse:
    container_name: pan-clickhouse
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_PASSWORD: clickhouse
      CLICKHOUSE_USER: default
    healthcheck:
      test:
        - CMD-SHELL
        - clickhouse-client --password clickhouse --query "SELECT 1" || exit 1
      timeout: 10s
      interval: 30s
      retries: 3
      start_period: 30s
    image: clickhouse/clickhouse-server:latest
    networks:
      macvlan_net:
        ipv4_address: 192.168.33.223
    restart: unless-stopped
    volumes:
      - type: bind
        source: /space/projects/pan-dashboard/docker/clickhouse_data
        target: /var/lib/clickhouse
        bind:
          create_host_path: true
  grafana:
    container_name: pan-grafana
    depends_on:
      clickhouse:
        condition: service_started
        required: true
    environment:
      GF_INSTALL_PLUGINS: grafana-clickhouse-datasource
      GF_SECURITY_ADMIN_PASSWORD: panzura
      #GF_SERVER_ROOT_URL: https://viperdavethesnake.duckdns.org/pan/dashboards
      #GF_SERVER_SERVE_FROM_SUB_PATH: "true"
    healthcheck:
      test:
        - CMD-SHELL
        - curl -fsS --connect-timeout 3 --max-time 5 http://localhost:3000/api/health || exit 1
      timeout: 10s
      interval: 30s
      retries: 3
      start_period: 30s
    image: grafana/grafana:latest
    network_mode: service:clickhouse
    restart: unless-stopped
    volumes:
      - type: bind
        source: /space/projects/pan-dashboard/docker/grafana_data
        target: /var/lib/grafana
        bind:
          create_host_path: true
      - type: bind
        source: /space/projects/pan-dashboard/docker/grafana/provisioning
        target: /etc/grafana/provisioning
        bind:
          create_host_path: true

  importer:
    container_name: pan-importer
    command:
      - sh
      - -c
      - pip install --quiet clickhouse-connect && python import_data.py
    depends_on:
      clickhouse:
        condition: service_healthy
        required: true
    image: python:3.12-slim
    network_mode: service:clickhouse
    profiles:
      - tools
    volumes:
      - type: bind
        source: /space/projects/pan-dashboard/docker/data
        target: /data
        bind:
          create_host_path: true
      - type: bind
        source: /space/projects/pan-dashboard/scripts
        target: /app
    working_dir: /app

  ai-query-service:
    build:
      context: /space/projects/pan-dashboard/docker/ai-query-service
      dockerfile: Dockerfile
    container_name: pan-ai-query
    depends_on:
      clickhouse:
        condition: service_healthy
        required: true
    healthcheck:
      test:
        - CMD-SHELL
        - curl -fsS --connect-timeout 3 --max-time 5 http://localhost:5000/health || exit 1
      timeout: 10s
      interval: 30s
      retries: 3
      start_period: 30s
    network_mode: service:clickhouse
    restart: unless-stopped

  open-webui:
    container_name: pan-open-webui
    depends_on:
      ai-query-service:
        condition: service_healthy
        required: true
    environment:
      OLLAMA_BASE_URL: http://192.168.33.197:11434
      OPENAI_API_BASE_URL: "http://localhost:5000/v1"
      OPENAI_API_KEY: "dummy-key"
      WEBUI_AUTH: "False"
      DEFAULT_MODELS: "file-query-assistant"
      DEFAULT_USER_ROLE: "user"
      ENABLE_SIGNUP: "False"
      WEBUI_NAME: "Pan-Dashboard File Query"
    healthcheck:
      test:
        - CMD-SHELL
        - curl -fsS --connect-timeout 3 --max-time 5 http://localhost:8080/health || exit 1
      timeout: 10s
      interval: 30s
      retries: 3
      start_period: 30s
    image: ghcr.io/open-webui/open-webui:latest
    network_mode: service:clickhouse
    restart: unless-stopped
    volumes:
      - type: bind
        source: /space/projects/pan-dashboard/docker/open-webui-data
        target: /app/backend/data
        bind:
          create_host_path: true

networks:
  macvlan_net:
    name: macvlan_net
    external: true
