services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: pan-clickhouse
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native protocol
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=clickhouse
    networks:
      - pan-network

  grafana:
    image: grafana/grafana:latest
    container_name: pan-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=panzura
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
    networks:
      - pan-network
    depends_on:
      - clickhouse

volumes:
  clickhouse_data:
  grafana_data:

networks:
  pan-network:
    driver: bridge
